//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public int id_s { get; set; }
        public Nullable<int> id_sal { get; set; }
        public Nullable<int> id_prem { get; set; }
        public string surname { get; set; }
        public string C_name { get; set; }
        public string middlename { get; set; }
        public string education { get; set; }
        public Nullable<System.DateTime> dateofbirth { get; set; }
        public Nullable<System.DateTime> dateofstartjob { get; set; }
        public Nullable<int> series_p { get; set; }
        public Nullable<int> number_p { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string password { get; set; }
        public string login { get; set; }
        public Nullable<int> id_p { get; set; }
        public string salt { get; set; }
        public string hashedpassword { get; set; }
        public string hashpaswor { get; set; }
        public string salts { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Premium Premium { get; set; }
        public virtual Salary Salary { get; set; }
    }
}
